### ISSUE TITLE
git-checkout lacks any authentication paramaters

### ISSUE THREAD

**Issue by andy-welsh-dwp** [chainguard-dev/melange#1112]
The [git-checkout pipeline](https://edu.chainguard.dev/open-source/melange/melange-pipelines/git-checkout/) does not appear to have any paramaters or obvious ways to authenticate against a private repository.

Typically the easiest way to get authentication in to a clone or checkout is by manipulating the git URI, I.E.:

`git clone https://$username:$password@gitlab.com/privaterepo`

Doing this in a secure system needs some kind of way to inject a secret. Currently I am able to inject an environment variable containing such a secret, however when running:

```yaml
- uses: git-checkout
  with:
    repository: https://myuser:${GIT_SECRET}@gitlab.com/privaterepo
    branch: somebranch
    destination: privaterepo
```

`$GIT_SECRET` does not appear to be evaluated and authentication fails as if it weren't there.

As a workaround currently, I can use:

```yaml
- runs: |
    git clone https://myuser:${GIT_SECRET}@gitlab.com/privaterepo -b somebranch
```

Thanks!
