### ISSUE TITLE
Strict validation of pipeline inputs

### ISSUE THREAD

**Issue by jdolitsky** [chainguard-dev/melange#1123]
When using 
```
  - uses: go/build
    with:
      packages: .
      output: demo
      go-packages: go-other # wrong input name, should be "go-package"
 ```

The `go-packages` input is wrong (should be `go-package`) but pipeline does not fail, instead ignores the input and uses the default value. Go pipeline: https://github.com/chainguard-dev/melange/blob/dfc2c1eb5a0c43d6a375dc2c1d3d78fa6c8c2493/pkg/build/pipelines/go/build.yaml#L10
