### ISSUE TITLE
[feature request] cmake/test pipeline for working with the cmake/build pipeline

### ISSUE THREAD

**Issue by IceCodeNew** [chainguard-dev/melange#1245]
# Use case

```yaml
package:
  name: snmalloc
  version: "0.6.2"
  epoch: 0
  description: "snmalloc is a high-performance, message passing based allocator."
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - glibc

environment:
  contents:
    packages:
      - clang-18
      # ...

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/microsoft/snmalloc/archive/refs/tags/${{package.version}}.tar.gz
      expected-sha256: e0486ccf03eac5dd8acbb66ea8ad33bec289572a51614acdf7117397e4f1af8c

  - uses: cmake/configure
    with:
      opts: |
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=clang \
          -DCMAKE_CXX_COMPILER=clang++ \
          -DSNMALLOC_BUILD_TESTING=OFF \
          -DSNMALLOC_LINK_ICF=ON \
          -DSNMALLOC_IPO=ON \
          -DSNMALLOC_STATIC_LIBRARY_PREFIX=
  - uses: cmake/build

  # The following instructions do not work as there is no test available.
  # Even it works, it still makes sense to have a cmake/test pipeline
  #    so we can have a unanimous framework for C/C++ projects.
  - runs: |
      ctest --output-on-failure -j "$(nproc)" -C Release --timeout 400

  - uses: cmake/install
```
