### ISSUE TITLE
RFE: git-cherry-pick pipeline

### ISSUE THREAD

**Issue by smoser** [chainguard-dev/melange#1273]
I'd like to request a git-cherry-pick pipeline for applying patches.
The use case can be seen https://github.com/wolfi-dev/os/pull/21949

For cherry-picking an upstream patch, the current method is:
 * get the patch in .patch format into a file
 * list patch file in 'patches' pipeline

The problem with this is that it takes manual effort to document where the patch came from, and allows for unintentional/accidental changes to creep in. It also provides no easy way for the reviewer of a PR to verify that the submitter did a good job.

A git cherry-pick work flow would streamline a this to just referencing a git commit in the same repository as the git clone.

```
- uses: git-cherry-pick
    with:
      commits: |
         1c95d96411de59379a043fa4e60f15f7862433d3 # Handle empty param in EVP_PKEY_CTX_add1_hkdf_info 
         77995ed7fff59c07a67eb03d6c6453115c3772cf  #...
```

I would like to be able to somehow easily comment as shown above, it'd be nice if we had some other tool to automatically add a cherry pick and make the appropriate comment.

**Comment by smoser** [comment]
I mentioned to @krishjainx that adding cherry-picks to the git-checkout pipeline might be easier.

the normal usage would look like this:
```yaml
  - uses: git-checkout
    with:
      expected-commit: 73d317384c9225e46d66444f93b46f0fbe7084ef
      repository: https://git.code.sf.net/p/zsh/code
      tag: zsh-5.9
      cherry-picks: |
        # CVE-2023-48795
        master/9dcaf78997508f45105f11a28932fcb6b113d27e
        # CVE-2023-39325
        master/efb7a962073988b4212820b02017980f5ec83f38
 ```
 
 The idea is cherry-picks would be newline separated with <branch>/<hash> . if <branch> not present you can try to just get it, but i dont think that will work (if you can figure out how to make it work, that'd be great).
and allow for # comments
