### ISSUE TITLE
Create an apk package to install company certs

### ISSUE THREAD

**Issue by Conor-Behard333** [chainguard-dev/melange#1275]
Hi,

I'm looking at using apko and melange as an alternative to docker. Normally in our dockerfiles we have to copy in any relevant company certs so that communicating with on-prem services is possible over https.

Usually done like:
cp certs-location /usr/local/share/ca-certificates
Update-ca-certificates

I've been stuck trying to do this using a custom apk. I've been able to move the certs into

**Comment by Conor-Behard333** [comment]
I've been able to move the certs into the apko build, but update-ca-certificates command is not running so the trusted certs are not trusted. 
custom apk packagec config:
```YAML
package:
  name: certs
  version: v0.1.0
  epoch: 0
  description: "certs"
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
    packages:
      - busybox
      - ca-certificates

pipeline:
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/share/ca-certificates
      cp ./certs/* ${{targets.destdir}}/usr/local/share/ca-certificates
      update-ca-certificates
      
```

apko yaml config:
```YAML
contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
    - "@local packages"
  packages:
    - cosign=2.2.4
    - vault=1.13.0
    - wolfi-base
    - certs@local
    - curl
    - busybox
    - ca-certificates

accounts:
  users:
    - username: base
      uid: 65532
      gid: 65532
  run-as: 65532

entrypoint:
  command: /bin/sh -l

archs:
  - x86_64
  
```

**Comment by Conor-Behard333** [comment]
Though adding a scriptlet would work but still does not work.
```YAML
scriptlets:
    post-install: |
      #!/bin/busybox sh
      update-ca-certificates
```
