### ISSUE TITLE
 host arch bwrap: execvp /bin/sh: No such file or directory

### ISSUE THREAD

**Issue by Lunarequest** [chainguard-dev/melange#129]
I'm currently trying to build a rust project using melange as a apk for apko. After it installs everything and reaches the runs section the following error occurs 
```
2022/10/07 13:05:53 melange (Lunas-blog/x86_64): bwrap: execvp /bin/sh: No such file or directory
2022/10/07 13:05:53 melange (Lunas-blog/x86_64): warning: read |0: file already closed
```
I originally ran into this with foreign arch's such as `aarch64`. I've already got `systemd-binfmt` setup. I tried using the recommended command.
```
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes 
```
but that doesn't change the output, I tried limiting to the host arch `amd64` but the same error occurs regardless. I've tried using `podman` instead of docker but that changes nothing

**Comment by Lunarequest** [comment]
my melange.yaml if required
```yaml
package:
  name: Lunas-blog
  version: 0.1.0
  description: Luna's blog
  target-architecture:
    - amd64
    - aarch64
  copyright:
    - license: GPL-2.0-only
      paths:
        - "*"
  dependencies:
    runtime:
      - libpq
      - openssl

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - ca-certificates-bundle
      - musl-dev 
      - pkgconf 
      - openssl-dev
      - libpq-dev
      - rust
pipeline:
  - name: Build Luna's blog
    runs: |
      EXEC_DIR="${{targets.destdir}}/usr/bin"
      BLOG_HOME="${{targets.destdir}}/opt/blog"
      MEDIA_HOME="${{targets.destdir}}/opt/blog/media"
      mkdir -p "${BLOG_HOME}" "${EXEC_DIR}" "${MEDIA_HOME}"
      cargo update
      cargo build --release
      cp target/release/blog "${EXEC_DIR}"
      cp -r templates "${BLOG_HOME}"% 
```
