### ISSUE TITLE
Melange regression w.r.t. working-directory handling in a sub-pipeline with uses: sub-pipeline

### ISSUE THREAD

**Issue by xnox** [chainguard-dev/melange#1311]
Full details in:

https://github.com/wolfi-dev/os/pull/22249/files#r1646501845

In essence:

```yaml
-pipeline:
  - working-directory: /home/build/go
    pipeline:
      # is good and runs in /home/build/go
      - runs: |
          echo $(pwd) should be /home/build/go
     # is bad and runs in /home/build
      - uses: patch
        with:
          patches: /home/build/000-initial-setup.patch
```
