### ISSUE TITLE
RFC / RFE - testing python with more than just 'import'

### ISSUE THREAD

**Issue by smoser** [chainguard-dev/melange#1367]
The `python/import` test is very nice, with 'imports' and makes testing import very easy.  I'd like to be able to do some more complex tests, and thought a pipeline would be useful.

The py3-pytest-timeout package currently has a [test](https://github.com/wolfi-dev/os/blob/41fd54bb68d10033d2b1002509c04a274b18c165/py3-pytest-timeout.yaml) that uses py3-pytest.  Its `[test](https://github.com/wolfi-dev/os/blob/41fd54bb68d10033d2b1002509c04a274b18c165/py3-pytest-timeout.yaml#L40)` stanza is kind of cludgy involving shell grep/exit, which is painful and has high potential for footgun.

I think it would be nice to have at very least something like this:

```yaml
test:
  pipeline:
    - uses: python/tests
      tests:
       - content: |
           import foo
           assert(foo.version == "${{package.version}}")
       - content: |
           import bar
           ....
```

My second thought there is that it might be useful to run those with `pytest`, to allow the sort of things that pytest buys you.

```yaml
test:
  pipeline:
    - uses: python/tests
      tests:
        - content: |
          import time
          def test_verify_stuff():
             """verify the stuff"""
             ...
```

Things I like about this:
 * it is all in the yaml file - you don't have to go lookiong elsewhere, and changes to the package aren't possibly "hidden" in a <package>/ directory.
 * one place to execute the things (the python) so each yaml file doesn't have to implement a correct execution

Things I don't like:
 * it is all in the yaml file - makes long noisy yaml files and not so easy to just run the same tests manually.

This is a RFC/RFE, I _really_ think we can do better with tests and I think we need to, so that writing them is easier.
