### ISSUE TITLE
Improve package compatibility with repology - U field missing inside APKIndex files

### ISSUE THREAD

**Issue by lioneloh** [chainguard-dev/melange#1368]
**Problematic** :

Repology cannot scan and expose the wolfi distribution package because the URL field inside the APKIndex yaml file is missing.

**Summary** :

Repology is the API used by Renovate and other tools to detect and automate version bump. After this improvement, we could have wolfi distribution integrated to repology and all apko for docker file could be scanned by Renovate to detect version bump of packages in a automated way.

**Proposed changes** :

Add the U field (URL field) inside APKIndex generated by melange. This U field could be populated through a new yaml declaration at package level

example 
```yaml
package:
  name: bash
  version: 5.2.21
  epoch: 5
  description: "GNU bourne again shell"
  url: "https://www.gnu.org/software/bash/bash.html"
  copyright:
    - license: GPL-3.0-or-later
```

Related issue : https://github.com/repology/repology-updater/issues/1339
