### ISSUE TITLE
bubblewrap environment does not include HOME in test, docker runner does

### ISSUE THREAD

**Issue by smoser** [chainguard-dev/melange#1407]
As seen https://github.com/wolfi-dev/os/commit/9a36346964d080e69196746ea5b804d5363b3280
I have had to add 'HOME' to the environment for running of tests in order for them to run on bwrap runner.

The build environment does get HOME=/home/build but test environment it is not set.

Given the yaml below, with my melange:
```
$ melange version | grep '^[A-Z]'
GitVersion:    v0.11.1-31-g4b59659
GitCommit:     4b59659dbfa5c422a79e059d4585806abaa0d4e1
GitTreeState:  clean
BuildDate:     '2024-07-29T15:47:22Z'
GoVersion:     go1.22.5
Compiler:      gc
Platform:      linux/amd64
```

Running this `test-me.yaml`:

```yaml
package:
  name: test-me
  version: 1.0
  epoch: 0

environment:
  contents:
    packages:
      - busybox

pipeline:
  - runs: |
      showhome=${{targets.contextdir}}/usr/bin/show-home
      mkdir -p $(dirname "$showhome")
      printf '#!/bin/sh\necho HOME="$HOME"\n' > "$showhome"
      chmod 755 "$showhome"

      echo === build says ===
      "$showhome"

test:
  pipeline:
    - name: Run the showhome
      runs: |
        out=$(show-home)
        echo "got: $out"
        case "$out" in
          *HOME=) echo "home not set"; exit 1;;
          *HOME=) echo "got home=${out#HOME=}";;
        esac
```

We see:

    $ make MELANGE_EXTRA_OPTS=--runner=docker test/test-me
    /home/smoser/go/bin/melange test test-me.yaml \
         --repository-append /home/smoser/src/wolfi/os/packages \
         --keyring-append local-melange.rsa.pub --arch x86_64 \
         --pipeline-dirs ./pipelines/ \
         --repository-append https://packages.wolfi.dev/os \
         --keyring-append https://packages.wolfi.dev/os/wolfi-signing.rsa.pub \
         --test-package-append wolfi-base \
         --debug --runner=docker --source-dir ./test-me/
    ...
    2024/07/29 12:44:40 INFO got: HOME=/root

But with bwrap, we see:

    $ make MELANGE_EXTRA_OPTS=--runner=bubblewrap test/test-me
    melange test test-me.yaml --repository-append /home/smoser/src/wolfi/os/packages \
         --keyring-append local-melange.rsa.pub --arch x86_64 --pipeline-dirs ./pipelines/ \
        --repository-append https://packages.wolfi.dev/os \
        --keyring-append https://packages.wolfi.dev/os/wolfi-signing.rsa.pub \
        --test-package-append wolfi-base --debug \
        --runner=bubblewrap --source-dir ./test-me/
    ...
    2024/07/29 12:45:05 WARN + '[' -d /home/build ]
    2024/07/29 12:45:05 WARN + cd /home/build
    2024/07/29 12:45:05 WARN + show-home
    2024/07/29 12:45:05 INFO got: HOME=
    2024/07/29 12:45:05 INFO home not set
    2024/07/29 12:45:05 WARN + out='HOME='
    2024/07/29 12:45:05 WARN + echo 'got: HOME='
    2024/07/29 12:45:05 WARN + echo 'home not set'
    2024/07/29 12:45:05 WARN + exit 1
