### ISSUE TITLE
support range replacer in pipeline needs

### ISSUE THREAD

**Issue by pnasrat** [chainguard-dev/melange#1444]
Following in `pkg/config/config_test.go`

```go
	require.Equal(t, cfg.Subpackages[0].Pipeline[0].Needs.Packages, []string{"a"})
	require.Equal(t, cfg.Subpackages[0].Pipeline[1].Needs.Packages, []string{"b"})
```

```yaml
package:
  name: range-substitutions
  version: 0.0.1
  epoch: 7
  description: example using a range in subpackages

data:
  - name: I-am-a-range
    items:
      a: 10
      b: 20

vars:
  buildLocation: "/home/build/foo"

subpackages:
  - range: I-am-a-range
    name: ${{range.key}}
    description: Check priorities are ${{range.value}}
    dependencies:
      provider-priority: ${{range.value}}
      replaces-priority: ${{range.value}}
      runtime:
        - wow-some-kinda-dynamically-linked-library-i-guess=1.0
    pipeline:
      - needs:
          packages:
            - ${{range.key}}  
        working-directory: ${{vars.buildLocation}}/subdir/${{range.key}}/${{range.value}}
        runs: |
          echo "$PWD
```
