### ISSUE TITLE
Melange does not expand vars in environment.environment of test

### ISSUE THREAD

**Issue by pnasrat** [chainguard-dev/melange#1478]
Melange does not expand vars in environment.environment of test

```
test:                                                                                                                                                                                                                                                                                                                         
  environment:                                                                                                                                                                                                                                                                                                                
    contents:                                                                                                                                                                                                                                                                                                                 
      packages:                                                                                                                                                                                                                                                                                                               
        - wolfi-base                                                                                                                                                                                                                                                                                                          
        - busybox                                                                                                                                                                                                                                                                                                             
    environment:                                                                                                                                                                                                                                                                                                              
      LD_LIBRARY_PATH: "/usr/local/cuda-${{vars.cuda-version}}/lib64:/usr/local/cuda-12.6/lib64/stubs:/usr/local/cudnn-8.9/lib64"                                                                                                                                                                                             
  pipeline:                                                                                                                                                                                                                                                                                                                   
    - runs: |                                                                                                                                                                                                                                                                                                                 
        echo $LD_LIBRARY_PATH  
```
