### ISSUE TITLE
local repository prints error, but works?

### ISSUE THREAD

**Issue by ckoehler** [chainguard-dev/melange#1584]
If I define a local repo in my melange file, it successfully uses packages from there, but prints this misleading error:

```
2024/10/21 15:28:22 ERRO request failed error="Get \"@local%20./packages/apk-configuration\": unsupported protocol scheme \"\"" method=GET url=@local%20./packages/apk-configuration
2024/10/21 15:28:22 WARN ignoring missing keys for @local ./packages: failed to perform key discovery: Get "@local%20./packages/apk-configuration": GET @local%20./packages/apk-configuration giving up after 1 attempt(s): Get "@local%20./packages/apk-configuration": unsupported protocol scheme ""
```

The section of the yaml file:

```yaml
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - '@local ./packages'
```
