### ISSUE TITLE
[cargo]: cargo/build pipeline improvements

### ISSUE THREAD

**Issue by kranurag7** [chainguard-dev/melange#1590]
This issue tracks improving our `cargo/build` pipeline to be more flexible and allow more wide usage of this pipeline across our package repositories.

We've certain limitations when we use cargo/build pipeline and below are the notes about the same.

1. As of now, the pipeline fails if we define a different modroot other than `.`

```yaml
  - name: build linkerd-network-validator
    uses: cargo/build
    with:
      modroot: ./validator
      output: linkerd-network-validator
      install-dir: lib/linkerd
```
The reason for failure here is that `cargo` stores the binary root of the tree under `target` directory. 
```bash
      cd "${{inputs.modroot}}"
```
In here, we change the directory to a different one and binary is stored at root.

After build, When we are invoking the `install` command in the pipeline it's not able to find the directory. 
```bash
        install -Dm755 "${OUTPUT_PATH}/${{inputs.output}}" "${INSTALL_PATH}/${{inputs.output}}"
```
The solution here is to use `CARGO_TARGET_DIR` environment variable but maybe there's also a simpler way to do this.

2. custom binary name 
unlike go `-o` flag, cargo doesn't have a similar flag but there's an experimental feature in cargo to specify custom binary name in there. 
https://doc.rust-lang.org/cargo/reference/unstable.html#different-binary-name

```bash
cargo new foo
cd foo
cargo run
cargo build
```
In above case, the binary name is always `foo`

If we want to change the binary name then we'll have to specify it something like this.
```toml
[[bin]]
name = "sammy"
path = "src/main.rs"
```
and then when we invoke `cargo build` or `cargo run` the binary name is `sammy`
