### ISSUE TITLE
Consider alternatives to document-wide templating

### ISSUE THREAD

**Issue by imjasonh** [chainguard-dev/melange#161]
Melange supports [templating using Go's template syntax](https://github.com/chainguard-dev/melange#build-file-templating), which I think is really good. I was surprised however to find that templating was applied _before_ parsing a melange.yaml file as YAML.

On the plus side, this means Melange supports meta-programming like [this](https://github.com/wolfi-dev/os/blob/e9cd19b6975a1975011ef716597be0e96ab16975/glibc.yaml#L228), which creates a subpackage per locale/language-name combo.

This also means that it's possible in theory to template anywhere in a Melange config, including keys:

```
package:
  name: description
  ${{package.name}}: lolwut
```

The downside of this is that a melange.yaml file on disk cannot be guaranteed to be parseable as YAML, which would let users leverage existing YAML tooling ([yq](https://mikefarah.gitbook.io/yq), [yamlfmt](https://github.com/google/yamlfmt), schema validators, other [YAML templating engines](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/) maybe, etc.), without having this built in to or otherwise supported by Melange.

I wonder if we should consider reducing the scope of the templating engine, and only have templates applied on (certain?) config values, and not document-wide.

The locale example above could be supported by relying on a shared pipeline (hard in this case because it's iteratively generating `subpackages` and not just pipeline steps), or a separate YAML-generation step that lives in wolfi-dev/os that gets checked in CI.

This would guarantee that Melange YAMLs are valid YAMLs, and let us leverage existing YAML tooling instead of having to invest it in it Melange itself.

If there's a broader thinking behind Melange's templating being done this way, that's fine, and that context would be helpful too -- it's totally possible that such powerful templates are more valuable than having parseable YAML.

I thought I'd bring this up pre-0.2 in case we decide to change course, since post-0.2 it becomes harder to put the genie back in the bottle.

**Comment by kaniini** [comment]
I think we should keep it as it is, because of the metaprogramming capabilities enabled by it.

**Comment by imjasonh** [comment]
> I think we should keep it as it is, because of the metaprogramming capabilities enabled by it.

That's completely reasonable. Can you give me an idea of what kinds of metaprogramming you have in mind, so I can understand how it outweighs the YAML benefits? I'm definitely willing to be convinced.

**Comment by kaniini** [comment]
The locales are an example.  It is also used already in this way inside chainguard images, such as to build multiple versions of nginx from a single melange yaml file.

**Comment by luhring** [comment]
I'm also concerned about naming files `*.yaml` that don't validate as YAML or work with YAML tooling. I think this makes our ecosystem more difficult to work with, for the same reasons @imjasonh mentioned above. It's also a bit tricky that there can be tokens like `${{targets.subpkgdir}}` and `{{$locale}}`, and you need to know that one is processed before YAML decoding and one is processed after.

At the same time, I'd love it if we could keep the benefits that metaprogramming is providing today. I don't doubt its value at all.

I'd like to understand what technical options we have for satisfying both of these concerns at the same time.

**Comment by imjasonh** [comment]
> The locales are an example. It is also used already in this way inside chainguard images, such as to build multiple versions of nginx from a single melange yaml file.

Oh, I see, like https://github.com/chainguard-images/nginx/blob/3bb2d381cc5a9f0cf633e2ff7a6681ada4e71652/melange.yaml#L3

I don't think supporting that is necessarily incompatible with my proposal, but I may not have elaborated it well.

My proposal would be that we have Melange parse as YAML first, then walk the tree and apply the templating only to leaf values. So `version: ${{ .Version }}` would still produce the same thing as today.

The locales wouldn't be supported in that world, but we could use a separate Melange subcommand, or a separate tool, to generate `glibc.yaml` with all the locales subpackages.

I think the question is whether we expect there to be lots of use cases for the kind of dynamic subpackage generation we see with locales in other packages -- if there are, then generating YAMLs in all those cases will get ugly.

**Comment by kaniini** [comment]
There are many packages in Alpine where dynamic generation of subpackages happens.  I think it should remain as it is, and we should deprecate the `.yaml` extension in favor of something else, maybe `Melangefile`.

**Comment by luhring** [comment]
I'm okay with changing the `.yaml` extension to a `.melangefile` (or whatever) extension, because I think it both **a)** enables the metaprogramming benefits while **b)** not breaking people's existing tooling. But my concern here would be that we've now created a very custom file format that's not YAML and it's not Go templates, and it's not clear to me if this is a necessary situation to be in. If we do go this route, we should prioritize having an awesome exported library function in Melange that helps you consume data of this type.

**Comment by luhring** [comment]
I'd love for us to consider solving this with just YAML. I've been impressed with how elegant Melange has already been in allowing efficient expression in YAML via mechanisms like "pipelines".

As an example, I took a look at the "locales" case, and tried to think about how we could make this work in Melange YAML.

```yaml
data:
  - name: "locales"
    kind: dict
    variables:
      key: "locale"
      value: "languageName"
    content:
      "aa": "Afar"
      "af": "Afrikaans"
      "agr": "Aguaruna"
      "ak": "Akan"
      "am": "Amharic"
      # etc.

subpackages:
  - range: "locales" # Ranges across the "locales" data object (which is a dict in this case) and produces subpackages according to the specification here
    name: "glibc-locale-{{$locale}}"
    description: "{{$languageName}} locale data for glibc"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/locale
          [ -d "${{targets.destdir}}"/usr/lib/locale/{{$locale}} ] \
            || mv "${{targets.destdir}}"/usr/lib/locale/{{$locale}}_* "${{targets.subpkgdir}}"/usr/lib/locale/
          [ -d "${{targets.destdir}}"/usr/lib/locale/{{$locale}} ] \
            && mv "${{targets.destdir}}"/usr/lib/locale/{{$locale}} "${{targets.subpkgdir}}"/usr/lib/locale/

```
