### ISSUE TITLE
Add variable to provide project source directory

### ISSUE THREAD

**Issue by wojciechka** [chainguard-dev/melange#1665]
This variable would be helpful when trying to create paths relative to base / source directory when using a pipeline with `working-directory` - for example:

```yaml
subpackages:
  - name: subpackage
    pipeline:
      # create files inside ${{targets.subpkgdir}} from other sources
      - uses: patch
        working-directory: "${{targets.subpkgdir}}"
        with:
          patches: "update-files-in-subpkgdir.patch"
```

This fails as the `patch.yaml` logic is reading files from current directory.

Something like this would work assuming a variable would be created:

```yaml
subpackages:
  - name: subpackage
    pipeline:
      # create files inside ${{targets.subpkgdir}} from other sources
      - uses: patch
        working-directory: "${{targets.subpkgdir}}"
        with:
          patches: "${{package.srcdir}}/update-files-in-subpkgdir.patch"
```
