### ISSUE TITLE
Idea: melange init

### ISSUE THREAD

**Issue by imjasonh** [chainguard-dev/melange#177]
It'd be cool to have a command to scaffold out a basic melange.yaml file. As a strawman, a basic `melange init` could emit a file containing:

```
package:
  name: TODO
  version: TODO
  epoch: 0
  description: TODO
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: TODO
  dependencies:
    runtime:
     # - TODO

environment:
  contents:
    repositories:
     # - TODO
    keyring:
     # - TODO
    packages:
     # - TODO

pipeline:
 # - name: TODO
 #   runs: TODO
```

This could be expanded with options like `melange init --package-repo=alpine` or `wolfi`, which would populate the `.environment.contents.repositories` and `keyring` with those values.

(If this sounds good we could also consider an `apko init`, with similar `--package-repo` flag, and a `--nonroot` flag to spit out the nonroot user boilerplate)

cc @eddiezane who actually had this idea
