### ISSUE TITLE
`var-transforms` do not provide a mechanism for mutating dissimilar inputs to the same variable

### ISSUE THREAD

**Issue by OddBloke** [chainguard-dev/melange#1774]
`opa-envoy` uses a versioning scheme of `<upstream version>-envoy<local revision>` but `<local revision>` is omitted for the first release. So, for example, the last two versions currently are `1.1.0-envoy-1` and `1.0.0-envoy`. These aren't valid APK versions (per https://github.com/wolfi-dev/wolfictl/blob/b168a068d4ea555968116a7577964310adf8ec33/pkg/versions/validate.go#L8-L23) so we need to mutate these to strings that are: respectively, `1.1.0-r1` (that's not an epoch!) and `1.0.0`.

The `version-transform` logic correctly mutates from the upstream version to the versions we want, but we then need to mutate back from the APK version to the upstream naming schema, to checkout the appropriate tag. Due to the absence of the `-0` on the upstream versioning in the "first release" case, there isn't a single regex match/replace that can do the job. `^(\d+\.\d+\.\d+)$` -> `$1-envoy` handles the first version case, and `^(.+)-r(\d+)$` -> `$1-envoy-$2` handles the subsequent versions case. This maps simply enough into melange configuration:

```
var-transforms:
  - from: ${{package.version}}
    # 1.0.0 -> 1.0.0-envoy
    match: ^(\d+\.\d+\.\d+)$
    replace: $1-envoy
    to: mangled-package-version
  - from: ${{package.version}}
    # 1.0.0-r2 -> 1.0.0-envoy-2
    match: ^(.+)-r(\d+)$
    replace: $1-envoy-$2
    to: mangled-package-version
```

However, this configuration doesn't work: melange [applies `var-transforms` in order, overwriting any previous values](https://github.com/chainguard-dev/melange/blob/main/pkg/config/vars.go#L66-L80), meaning that this configuration will only handle the `1.1.0-r1` case. If the stanzas were reversed, the configuration would only handle the `1.0.0` case.

Ideally, it would be possible to specify that a transform should be applied if and only if its match regex actually matches the `from` input. If there was, e.g., a `must-match: true` option we could apply here, then only the actually applicable stanza's output would be used for `mangled-package-version`, solving the problem.
