### ISSUE TITLE
compatibility with Chimera Linux?

### ISSUE THREAD

**Issue by ayushnix** [chainguard-dev/melange#1816]
Is melange compatible with Chimera Linux repositories? It also uses the apk package manager.

I tried building a rust image using the following `melange.yml` file

```
package:
  name: agate
  version: 3.3.13
  epoch: 0
  description: "simple server for the gemini protocol"
  copyright:
    - license: "Apache-2.0 OR MIT"

environment:
  contents:
    repositories:
      - "https://repo.chimera-linux.org/current/main"
    packages:
      - "base-files"
      - "ca-certificates"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mbrubeck/agate
      tag: v${{package.version}}
      expected-commit: 1143fe2ca1d44e545bb540b1d7bd5f2b262e403b
  - uses: cargo/build
    with:
      output: ${{package.name}}
  - uses: strip

update:
  github:
    identifier: mbrubeck/agate
    strip-prefix: v
    tag-filter-prefix: v
```

and the following command

```
melange build --ignore-signatures --apk-cache-dir $XDG_CACHE_HOME --arch aarch64 --signing-key melange.rsa melange.yaml
```

but I got this error

```
failed to build package: unable to build guest: unable to lock image configuration: resolving apk packages: for arch "arm64": error getting repository indexes: reading index https://repo.chimera-linux.org/current/main/aarch64/APKINDEX.tar.gz: parsing https://repo.chimera-linux.org/current/main/aarch64/APKINDEX.tar.gz: unable to read convert repository index bytes to index struct: gzip: invalid header
```
