### ISSUE TITLE
Failed to set capabilities on file 'setcap': Operation not supported

### ISSUE THREAD

**Issue by mbrancato** [chainguard-dev/melange#1876]
The use of `setcap` doesn't seem to work in a build. It always returns an error (which still allows an exit code of 0). The build will fail if you attempt to check the file afterwords. I've tried bubblewrap and docker runners.

```shell
setcap "cap_net_bind_service=+ep" /bin/foo
setcap -v "cap_net_bind_service=+ep" /bin/foo
```

example usage:
https://github.com/wolfi-dev/os/blob/545fce833d201848007eb36182cb3eaa7ab4a490/atlantis.yaml#L50

minimal reproducible example:
```yaml
package:
  name: setcap-demo
  version: "0"
  epoch: 0
  description: Demo setcap build failure in melange
  copyright:
    - license: Apache-2.0

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - libcap-utils
      - dumb-init

capabilities:
  add:
    - cap_sys_admin

pipeline:
  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/bin
      cp /usr/bin/dumb-init "${{targets.destdir}}"/usr/bin/dumb-init
      setcap "cap_net_bind_service=+ep" "${{targets.destdir}}"/usr/bin/dumb-init
      setcap -v "cap_net_bind_service=+ep" "${{targets.destdir}}"/usr/bin/dumb-init

```

**Comment by mbrancato** [comment]
I've identified this does work in a privileged container

```
docker run --privileged -v "$PWD":/work cgr.dev/chainguard/melange ...
```

It would be nice if we could just tell the `docker` runner to use privileged mode.

**Comment by mbrancato** [comment]
I've updated this minimal example to include a test. Even when run in a privileged container, the caps on the file are not preserved.

```yaml
package:
  name: setcap-demo
  version: "0"
  epoch: 0
  description: Demo setcap build failure in melange
  copyright:
    - license: Apache-2.0

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - libcap-utils
      - dumb-init
      - findmnt
      - gnutar

capabilities:
  add:
    - cap_sys_admin

pipeline:
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      cp /usr/bin/dumb-init ${{targets.destdir}}/usr/bin/dumb-init
      setcap "cap_net_bind_service=+ep" ${{targets.destdir}}/usr/bin/dumb-init
      setcap -v "cap_net_bind_service=+ep" ${{targets.destdir}}/usr/bin/dumb-init
      
test:
  environment:
    contents:
      repositories:
        - https://packages.wolfi.dev/os
      keyring:
        - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      packages:
        - busybox
        - libcap-utils

  pipeline:
    - runs: |
        setcap -v "cap_net_bind_service=+ep" /usr/bin/dumb-init
```

```shell
2025/03/28 12:11:29 INFO installing setcap-demo (0-r0)
2025/03/28 12:11:29 INFO built image layer tarball as /tmp/apko-temp-377001034/apko-aarch64.tar.gz
2025/03/28 12:11:29 INFO No source directory specified, skipping workspace population
2025/03/28 12:11:29 INFO running the main test pipeline
2025/03/28 12:11:29 INFO /usr/bin/dumb-init differs in [pe]
2025/03/28 12:11:29 ERRO ERROR: failed to test package. the test environment has been preserved:
2025/03/28 12:11:29 ERRO failed to test package: unable to run pipeline: unable to run pipeline: exit status 1
```
