### ISSUE TITLE
PATH set in environment.environment is not honored

### ISSUE THREAD

**Issue by apcheamitru** [chainguard-dev/melange#1956]
When `PATH` is set under the `environment.environment` block, it does not take.  Here's a `melange.yaml` that can be used to verify:

```
---
package:
  name: check-env
  version: 0.1.0
  epoch: 0
  description: Test package
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
  environment:
    FOO: bar
    PATH: /usr/bin

pipeline:
  - runs: |
      echo "FOO: $FOO"
      echo "PATH: $PATH"  # should be "/usr/bin"
```

The output shows that `FOO` is set correctly, but `PATH` is not.

```
2025/05/01 14:51:10 INFO FOO: bar
2025/05/01 14:51:10 INFO PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
```

I'm not sure if this is expected behavior, but it would be nice to have the ability to override `PATH` in the environment.
