### ISSUE TITLE
Default substitutions in environment

### ISSUE THREAD

**Issue by apcheamitru** [chainguard-dev/melange#1958]
Default substitutions cannot be used in environment blocks.  For example: 

```
---
package:
  name: check-env
  version: 0.1.0
  epoch: 0
  description: Test package
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
  environment:
    FOO: ${{build.arch}}

pipeline:
  - runs: |
      env | grep ^FOO=

  - runs: |
      env | grep ^BAR=
    environment:
      BAR: ${{build.arch}}
```

Building this package shows that both `FOO` and `BAR` are set to literal `"${{build.arch}}"`.  Is that expected behavior?

```
2025/05/01 19:21:36 INFO FOO=${{build.arch}}
2025/05/01 19:21:36 INFO BAR=${{build.arch}}
```

Melange version: 

```
bash-5.2# melange version
  __  __   _____   _          _      _   _    ____   _____
 |  \/  | | ____| | |        / \    | \ | |  / ___| | ____|
 | |\/| | |  _|   | |       / _ \   |  \| | | |  _  |  _|
 | |  | | | |___  | |___   / ___ \  | |\  | | |_| | | |___
 |_|  |_| |_____| |_____| /_/   \_\ |_| \_|  \____| |_____|
melange

GitVersion:    v0.23.11+dirty
GitCommit:     d06e39bbf3c2b716a84112fd509e5c49d436e6e1
GitTreeState:  clean
BuildDate:     '2025-04-28T01:24:17Z'
GoVersion:     go1.24.2
Compiler:      gc
Platform:      linux/amd64
```
