### ISSUE TITLE
Add gem/install pipeline

### ISSUE THREAD

**Issue by imjasonh** [chainguard-dev/melange#241]
```
pipeline:
  - uses: gem/install
    with:
      package: activerecord
      version: 7.0.4
```

runs

```
gem install activerecord --version=7.0.4
```

...and moves the installed gem into `${{targets.destdir}}` so it ends up in the apk

https://guides.rubygems.org/command-reference/#gem-install
