### ISSUE TITLE
Add php/composer-install pipeline

### ISSUE THREAD

**Issue by imjasonh** [chainguard-dev/melange#242]
```
pipeline:
  - uses: php/composer-install
    with:
      package: blah
      version: 1.2.3
```

runs

```
echo '{"require":{"blah":"1.2.3"}}` > composer.json
php composer install
```

(...or something, I don't know anything about PHP or composer. Help me @erikaheidi)

https://getcomposer.org/doc/03-cli.md#install-i
