### ISSUE TITLE
Add pipeline action to ensure a Go dependency is at least at a specified version

### ISSUE THREAD

**Issue by luhring** [chainguard-dev/melange#384]
### Problem

In order to fix vulnerabilities in a Go project, we've been inserting imperative commands into a package's Melange pipeline like this (taken from [here](https://github.com/wolfi-dev/os/blob/205999c770c888c47c4e9367f91f0c34719f35e4/terraform.yaml#L23-L24)):

```yaml
pipeline:
  # ...

  - runs: |
      # ...

      # Mitigate GHSA-vvpx-j8f3-3w6h
      go get golang.org/x/net@v0.7.0
```

This addresses the vulnerability, but there are a handful of issues with this approach:

1. Once the upstream project is using a version of the Go module that's **_later than_** the specified version (`v0.7.0` in this example), this command will start downgrading project dependencies, thereby potentially **introducing vulnerabilities** and breaking behavior for end users.
2. Removing this snippet from a package config is manual and error-prone.

### Proposed solution

It'd be great to have a declarative and reusable pipeline action to handle this scenario. I'm envisioning something like this:

```yaml
pipeline:
  # ...

  - uses: go/set-module-minimum-version
    with:
      project-dir: /<...>/terraform
      dependency: golang.org/x/net
      minimum-version: v0.7.0
```

The behavior here would be improved: this pipeline action would determine if the Go project is currently using a version of the specified dependency **_below_** the specified `minimum-version`, and if so, it would do the `go get ...`. Otherwise, it would leave the dependency version as is (i.e. at or above this version).

Further, this would allow us to add functionality in the future to programmatically determine which of these actions were no longer needed, and we could programmatically remove these YAML blocks to keep the config clean.

---

N.B.: This kind of pipeline action may be beneficial to other ecosystems beyond Go.
