### ISSUE TITLE
evaluate commands in ldflags for go/build pipeline

### ISSUE THREAD

**Issue by developer-guy** [chainguard-dev/melange#454]
it might not be a case but I noticed that the commands didn't executed and gave me the value of the command output when I use them in ldflags section of the go/build pipeline like the following:

```shell
  - uses: go/build
    with:
      packages: ./cmd/nri-kube-events
      ldflags: "-X 'main.integrationVersion=v${{ package.version }}' -X 'main.gitCommit=$(git rev-parse HEAD)' -X 'main.buildDate=$(date +%Y-%m-%dT%H:%M:%S%z)'"
      output: nri-kube-events
```

I saw the ldflags entries in the output of the Melange build, which showed me that commands executed only as strings are not treated as commands:

```shell
2023/05/20 20:47:00 melange (newrelic-nri-kube-events/x86_64):     ${{inputs.ldflags}}: -X 'main.integrationVersion=v2.0.0' -X 'main.gitCommit=$(git rev-parse HEAD)' -X 'main.buildDate=$(date +%Y-%m-%dT%H:%M:%S%z)'
```

So, we (w/@dentrax) thought that we may enable running commands in ldflags to overcome this problem, WDYT?

**Comment by kaniini** [comment]
the `with` block just provides raw strings.  this is by design.

a better approach would be to parse the output like github actions does, e.g.

```yaml
pipeline:
  - name: Compute build date
    id: date
    runs: |
      echo buildDate=$(date +%Y-%m-%dT%H:%M:%S%z) >> $MELANGE_OUTPUT

  - uses: go/build
    with:
      ...
      ldflags: ... -X 'main.buildDate=${{date.buildDate}}' ...
```

Though really in the case of build dates in particularly, we would want something which respects `SOURCE_DATE_EPOCH` rather than shelling out to `date`.
