### ISSUE TITLE
Melange pipelines should not transform input path values

### ISSUE THREAD

**Issue by luhring** [chainguard-dev/melange#461]
Currently, there's at least one Melange pipeline that accepts a path input, but Melange does hidden, non-obvious transformations to the user's path value, such that unexpected and difficult-to-debug effects end up in the built package.

For example:

Let's assume you want the binary to end up in `/usr/bin/foo`.

Is the following snippet correct?

```yaml
 - uses: go/build
    with:
      modroot: .
      packages: .
      output: ${{targets.destdir}}/usr/bin/foo
```

> Yes... right?

No.

> Ok, maybe it should be just `output: /usr/bin/foo`?

No.

> Okay, I give up, what?

The correct answer is:

```yaml
 - uses: go/build
    with:
      modroot: .
      packages: .
      output: foo
```

This will end up writing the file to what is referred to as `${{targets.destdir}}/usr/bin/foo` everywhere else in your Melange build config.

This makes for a rough user experience. Since Melange treats path values literally in so many places, with the help of variables like `${{targets.destdir}}`, users should be free to continue with those expectations in path-related pipeline input values and get sane results.
