### ISSUE TITLE
Permission and syntax error with resulting apk package

### ISSUE THREAD

**Issue by MathKlim** [chainguard-dev/melange#471]
Hi,

I just found melange and I think it's great, I tried it on a soft that I use quite a lot [terratag](https://github.com/env0/terratag), terraform and terragrunt are already provided as wolfi package but not this one, so I tried myself, with some inspiration coming from the `terraform.yaml` [melange file](https://github.com/wolfi-dev/os/blob/main/terraform.yaml) I get the following melange file.

```yaml
package:
  name: terratag
  version: 0.2.3
  copyright:
    - license: MPL-2.0
      paths:
        - "*"

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - ca-certificates-bundle
      - busybox
      - go

pipeline:
  - uses: "git-checkout"
    with:
      repository: https://github.com/env0/terratag
      tag: v${{package.version}}
      expected-commit: 6a704b4bd580edf2beba684312cb6a0a14e0b1ef

  - runs: |
      go mod tidy

  - uses: go/build
    with:
      packages: .
      output: terratag

  - uses: strip
```

I get an apk package, but when I tried to use it via `terratag --version` after having done an `apk add ....`, eg on an `alpine:latest` container I get the following error `ash: terratag: Permission denied`. If I do  `chmod +x terratag` and try again `terratag --version` I then get a `/usr/bin/terratag: line 2: syntax error: unexpected newline`.

That soft works well on ubuntu, so my guess is I've done something wrong during the apk package build, but I don't know what.

For the record, the way to build terratag provided in their repo is the following one : 

```bash
git clone https://github.com/env0/terratag
cd terratag
go mod tidy
go build ./cmd/terratag
```

I'm not sure the

```yaml
  - runs: |
      go mod tidy

  - uses: go/build
    with:
      packages: .
      output: terratag

  - uses: strip
 ```

part is completely equivalent to the shell commands above, so maybe that's why I can't use it.

Does anybody have any idea ?
