### ISSUE TITLE
Fetch should delete artifact after use to prevent stomping on other artifacts with same name

### ISSUE THREAD

**Issue by strongjz** [chainguard-dev/melange#484]
Artifacts with the same name will cause SHA mismatch errors 

```yaml
  - uses: fetch
     with:
       uri: https://github.com/openresty/set-misc-nginx-module/archive/v0.33.tar.gz
       expected-sha256: cd5e2cc834bcfa30149e7511f2b5a2183baf0b70dc091af717a89a64e44a2985
       strip-components: 0
 
   - uses: fetch
     with:
       uri: https://github.com/openresty/headers-more-nginx-module/archive/v0.33.tar.gz$
       expected-sha256: a3dcbab117a9c103bc1ea5200fc00a7b7d2af97ff7fd525f16f8ac2632e30fbf$
       strip-components: 0
````

Error 
````bash
if [ "a3dcbab117a9c103bc1ea5200fc00a7b7d2af97ff7fd525f16f8ac2632e30fbf" == "" ] && [ "" == "" ]; then
  printf "One of expected-sha256 or expected-sha512 is required"
  exit 1
fi

bn=$(basename https://github.com/openresty/headers-more-nginx-module/archive/v0.33.tar.gz)

if [ ! "a3dcbab117a9c103bc1ea5200fc00a7b7d2af97ff7fd525f16f8ac2632e30fbf" == "" ]; then
  fn="/var/cache/melange/sha256:a3dcbab117a9c103bc1ea5200fc00a7b7d2af97ff7fd525f16f8ac2632e30fbf"
  if [ -f $fn ]; then
    printf "fetch: found $fn in cache\n"
    cp $fn $bn
  fi
else
  fn="/var/cache/melange/sha512:"
  if [ -f $fn ]; then
    printf "fetch: found $fn in cache\n"
    cp $fn $bn
  fi
fi

if [ ! -f $bn ]; then
  wget -q -T5 --dns-timeout=20 --tries=5 --random-wait --retry-connrefused --continue https://github.com/openresty/headers-more-nginx-module/archive/v0.33.tar.gz
fi

if [ "a3dcbab117a9c103bc1ea5200fc00a7b7d2af97ff7fd525f16f8ac2632e30fbf" != "" ]; then
  printf "%s  %s\n" 'a3dcbab117a9c103bc1ea5200fc00a7b7d2af97ff7fd525f16f8ac2632e30fbf' $bn | sha256sum -c
else
  printf "%s  %s\n" '' $bn | sha512sum -c
fi

if [ "true" = "true" ]; then
  tar -x '--strip-components=0' -f $bn
fi

exit 0
⚠️  x86_64    | sha256sum: WARNING: 1 of 1 computed checksums did NOT match
ℹ️  x86_64    | v0.33.tar.gz: FAILED
2023/06/02 09:27:20 ERROR: failed to build package. the build environment has been preserved:
````

Workaround: 

Deleting artifacts between runs 

````yaml
   - uses: fetch
     with:
       uri: https://github.com/simpl/ngx_devel_kit/archive/v0.3.1.tar.gz
       expected-sha256: 0e971105e210d272a497567fa2e2c256f4e39b845a5ba80d373e26ba1abfbd85
       strip-components: 0
   - uses: fetch
     with:
       uri: https://github.com/openresty/set-misc-nginx-module/archive/v0.33.tar.gz
       expected-sha256: cd5e2cc834bcfa30149e7511f2b5a2183baf0b70dc091af717a89a64e44a2985
       strip-components: 0
 
   - runs: |
       rm -rf v0.33.tar.gz$
 
   - uses: fetch
     with:
       uri: https://github.com/openresty/headers-more-nginx-module/archive/v0.33.tar.gz
       expected-sha256: a3dcbab117a9c103bc1ea5200fc00a7b7d2af97ff7fd525f16f8ac2632e30fbf
       strip-components: 0
 
   - uses: fetch
     with:
       uri: https://github.com/atomx/nginx-http-auth-digest/archive/v1.0.0.tar.gz
       expected-sha256: f09851e6309560a8ff3e901548405066c83f1f6ff88aa7171e0763bd9514762b
       strip-components: 0
````
