### ISSUE TITLE
File Ownership not preserved

### ISSUE THREAD

**Issue by amouat** [chainguard-dev/melange#501]
When using `chown` or similar in melange, I would expect the changes to make it into the tar file, but this doesn't seem to be the case.

For example, with this melange file:

```
package:
  name: owntest
  version: 0.0.0
  epoch: 0
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
  accounts:
    users:
      - username: test
        uid: 1001

pipeline:
  - name: testy
  - runs: |
      touch file
      install -m744 -o test -D file ${{targets.destdir}}/etc/test/file
      chown test file
      cp file ${{targets.destdir}}/etc/
      chown test ${{targets.destdir}}/etc/file
      ls -l ${{targets.destdir}}/etc/file
      ls -l /${{targets.destdir}}/etc/test/file
      ls -l ${{targets.destdir}}/etc/test
```

I get the following results:

```
tar --same-owner -tpvf packages/aarch64/owntest-0.0.0-r0.apk
-rw-r--r--  0 root   root      209  1 Jan  1970 .PKGINFO
drwxr-xr-x  0 root   root        0  1 Jan  1970 etc
-rw-r--r--  0 root   root        0  1 Jan  1970 etc/file
drwxr-xr-x  0 root   root        0  1 Jan  1970 etc/test
-rwxr--r--  0 root   root        0  1 Jan  1970 etc/test/file
drwxr-xr-x  0 root   root        0  1 Jan  1970 var
drwxr-xr-x  0 root   root        0  1 Jan  1970 var/lib
drwxr-xr-x  0 root   root        0  1 Jan  1970 var/lib/db
drwxr-xr-x  0 root   root        0  1 Jan  1970 var/lib/db/sbom
-rw-r--r--  0 root   root     2875  1 Jan  1970 var/lib/db/sbom/owntest-0.0.0-r0.spdx.json
```

But I expected `/etc/file` and `/etc/test/file` to be owned by `test`.

The owner is `test` in the debug output from melange.
