### ISSUE TITLE
targets.subpkgdir not properly evaluated for range in working-directory

### ISSUE THREAD

**Issue by kaniini** [chainguard-dev/melange#602]
Consider the following:

```yaml
data:
  - name: foo
    items:
      a: A
      b: B
      c: C

subpackages:
  - range: foo
    pipeline:
      - working-directory: ${{targets.subpkgdir}}
        runs: |
          pwd
```

The output will be:

```
/home/build
...
/home/build
...
/home/build
```
