### ISSUE TITLE
options not copied when applying range to subpackages

### ISSUE THREAD

**Issue by kaniini** [chainguard-dev/melange#603]
Consider the following:

```yaml
data:
  - name: foo
    items:
      a: A
      b: B
      c: C

subpackages:
  - range: foo
    name: ${{range.key}}
    description: ${{range.value}}
    options:
      no-provides: true
```

The synthesized subpackages will actually have Options.NoProvides set to `false`.
