### ISSUE TITLE
pipeline environment blocks

### ISSUE THREAD

**Issue by kaniini** [chainguard-dev/melange#675]
Consider the following:

```yaml
package:
  ...

environment:
  ...
  environment:
    FOO: "bar"

pipeline:
  - environment:
      BAR: "baz"
    runs: |
      echo FOO: $FOO
      echo BAR: $BAR
```

This should print:

```
FOO: bar
BAR: baz
```

This should also do downward propagation, e.g.

```yaml
pipeline:
  - environment:
       BAR: "baz"
     pipeline:
       - runs: |
            echo FOO: $FOO
            echo BAR: $BAR
```

Should also print:

```
FOO: bar
BAR: baz
```
