### ISSUE TITLE
strip: Unable to recognise the format of the input file while using goreleaser/build

### ISSUE THREAD

**Issue by developer-guy** [chainguard-dev/melange#693]
I made an example to test newly created goreleaser/build pipeline with an example package named grpc-health-probe.yaml. Somehow, strip pipeline seems is not working and giving the following error:

>   aarch64   | strip: Unable to recognise the format of the input file `./usr/bin/grpc-health-probe'

The melange configuration file for the grpc-health-probe:

```yaml
package:
  name: grpc-health-probe
  version: 0.4.19
  epoch: 4
  description: A command-line tool to perform health-checks for gRPC applications in Kubernetes and elsewhere
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grpc-ecosystem/grpc-health-probe
      tag: v${{package.version}}
      expected-commit: 1089f40639043ee46cc47cbea1bcb0cc48cfc284
      destination: grpc-health-probe

  - uses: goreleaser/build
    with:
      args: --snapshot --debug
      working-dir: grpc-health-probe

  - uses: strip

subpackages:
  - name: grpc-health-probe-compat
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /bin
          mkdir -p "${{targets.subpkgdir}}"/bin
          ln -sf /usr/bin/grpc-health-probe ${{targets.subpkgdir}}/bin/grpc-health-probe
    dependencies:
      runtime:
        - grpc-health-probe

update:
  enabled: true
  github:
    identifier: grpc-ecosystem/grpc-health-probe
    strip-prefix: v
    use-tag: true
```

to reproduce the issue, you can run the following command:

```shell
melange build --arch aarch64 --pipeline-dir pkg/build/pipelines/ -r https://packages.wolfi.d
ev/os -k https://packages.wolfi.dev/os/wolfi-signing.rsa.pub grpc-health-probe.yaml
```
