### ISSUE TITLE
RFC: consider deprecating and removing `required-steps`

### ISSUE THREAD

**Issue by imjasonh** [chainguard-dev/melange#831]
`required-steps` was [added in 0.2.0](https://github.com/chainguard-dev/melange/blob/main/NEWS.md#major-changes-from-010-to-020) to guard the behavior of conditional steps.

It's fairly flexible in theory, but in practice it seems to only be used to guard that only one of (usually) a pair of conditional steps is run.

The semantics of `required-steps` can be confusing when nested pipelines are involved. For example, without testing it, I don't know whether I expect `required-steps` to count sub-pipelines' steps or not. In practice we don't do it today, but if we did I don't know what would happen. This undefined and untested behavior may bite us later.

Wolfi's uses of `required-steps`: https://github.com/search?q=repo%3Awolfi-dev%2Fos%20required-steps&type=code

I wonder if we could get the same functionality in practice with existing features, like `uses`/`with` and a built-in pipeline.

```
# fails if ${{build.arch}} is not among the list
- uses: required-archs
  with:
    archs: x86_64,aarch64
```

The other case, where you want to fetch one or another artifact based on the arch -- but not both -- can also just be done with an unguarded pair of `if`s:

```
- uses: fetch
  if: ${{build.arch}} == 'x86_64'
  with:
    uri: foo
- uses: fetch
  if: ${{build.arch}} == 'aarch64'
  with:
    uri: bar
- uses: required-archs # anything else fails
  with:
    archs: x86_64,aarch64
```

It's possible but unlikely that a bug in Melange would allow both branches to be taken, but it's equally likely that a bug in `required-steps` would let them both execute as well. Even if it did, we would expect that behavior to fail for one reason or another, rather than produce a bad package, especially with the additional lint checks we've added since 0.2.0.

**Comment by kaniini** [comment]
The purpose of the `required-steps` assertion guard was to measure whether or not a branch was taken in the pipeline, by counting the number of steps taken in the branch (must be greater than some configured number of steps).

This is, admittedly, clunky to hold and does not feel good to use, which is not desirable in a tool.

Therefore, I suggest an alternative design, something like:

```yaml
pipeline:
  - assertion-group: fetch-runtime
    pipeline:
       - if: ${{build.arch}} == 'x86_64'
         uses: fetch
         with:
           uri: ...
       - if: ${{build.arch}} == 'aarch64'
         uses: fetch
         with:
           uri: ...
   
  - assertion: ${{fetch-runtime.asserted}} == 'true'
```

The idea is that steps would inherit their parent's `assertion-group`, and if the step executed, the assertion group would be in `asserted` state.

Any step could then have an `assertion-group` assigned to it, for example:

```yaml
pipeline:
  - assertion-group: fetch-sources
    uses: fetch
      with: ...

  - assertion: ${{fetch-sources.asserted}} == 'true'
```

Interestingly, this could also be used for negative assertions, for example we could imagine something like the following:

```yaml
pipeline:
  - assertion-group: fetch-optimized-runtime
    pipeline:
      - ...

  - if: ${{fetch-optimized-runtime.asserted}} == 'false'
    warning: Optimized runtime is not fetched, package will be slow on ${{build.arch}}
```

Or perhaps:

```yaml
pipeline:
  - assertion-group: supported-arch
     pipeline:
        - if: ${{build.arch}} == 'x86_64' || ...
          runs: |
            exit 0

  - if: ${{supported-arch.asserted}} != 'true'
    error: Supported architecture check failed for ${{build.arch}}
```
