### ISSUE TITLE
Options no-depends: true gives error

### ISSUE THREAD

**Issue by aluakbe** [chainguard-dev/melange#845]
BUILD-FILE.md mention options
options:
  no-depends: true

When I tried to add this option, but it would give me this error: 
Error: failed to load configuration: unable to decode configuration file "melange.yaml": yaml: unmarshal errors:
  line 15: cannot unmarshal !!bool `true` into config.BuildOption
2023/11/15 08:45:50 error during command execution: failed to load configuration: unable to decode configuration file "melange.yaml": yaml: unmarshal errors:
  line 15: cannot unmarshal !!bool `true` into config.BuildOption

**Comment by debasishbsws** [comment]
It is working properly. You are getting an `yaml: unmarshal errors` that means that the yaml configuration has some issue.
I think you are trying to pass the [Package Options](https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md#options-1) and by mistake you have placed it in the place of [Build Options](https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md#options).

`no-depends` should be inside `package:`.
`package.no-depends = true/false`
```yaml
package:
  name: abc
  version: "0.0.0"
  ...
  ...
# this should be inside package.
  options:
    no-depends: true
    
environment:
  contents:
    packages:
...
...
```
