### ISSUE TITLE
RFC: `melange test --test-append`

### ISSUE THREAD

**Issue by imjasonh** [chainguard-dev/melange#938]
With the recent addition of `melange test`, packages can be tested for basic functionality, which is great.

We may have a set of common tests we want to run on many packages, which we could codify in a `tests/` directory, and pass to `melange test <pkg> --test-append=tests/` or `melange test <pkg> --test-append=tests/foo.yaml --test-append=bar.yaml`

The YAML file could include any extra `environment` to append, and pipeline steps to append:

```yaml
environment:
    contents:
      packages:
        - apk-tools
  pipeline:
    - runs: |
        apk add --simulate <pkg>
```

If this was run on a file which already contained tests, e.g.:

```yaml
test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        az --version
```

...then the resulting pipeline would be as if the file specified this:

```yaml
test:
  environment:
    contents:
      packages:
        - apk-tools
        - wolfi-base
  pipeline:
    - runs: |
        az --version
    - runs: |
        apk add --simulate <pkg>
```

That `<pkg>` makes me think we might need some basic templating, like `${{test.package}}` or something, so that the test pipeline is reusable.

WDYT @vaikas
